### PR TITLE
Ignore locally built binaries.

### PR DESCRIPTION
**Pull request by yegle**

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @yegle 

It's unclear why we need to ignore these. Can you just use `go run` instead?

**Comment by yegle** [comment]
Without this, it's a bit annoying to have to remove the binary before running the build script.

**Comment by sethvargo** [comment]
I'm still confused why you're building the binary though?

**Comment by yegle** [comment]
It's probably just me that will prefer running a built binary than using `go run`.

Anyway, I think this is cosmetic change. I'll revert and switch to use `go run`.

**Pull request closed without merging**
