### PR TITLE
complete removal of efgs config

### LINKED ISSUE #1146: remove EFGS DB columns
defer this one release to allow for smooth migration.

/assign

### PR DESCRIPTION
**Pull request by mikehelmick**
Fixes #1146

## Proposed Changes

* complete removal of EFGS DB columns

**Release Note**

```release-note
ALERT: If you are migration from 0.15 directly to 0.17 (skipping 0.16) you are at risk for DB column errors during upgrade.
This change removed DB columns that were dropped from use in v0.16.0
```

/assign @whaught 
/hold
Will hold until just before 0.17 is cut.

### CODE REVIEW

**Review by whaught — APPROVED** [review]
/lgtm

for the .17 cut

**Comment by mikehelmick** [comment]
/retest
with proper format to appease prow

**Review by sethvargo — APPROVED** [review]
/lgtm

**Pull request merged**
