### PR TITLE
Run terraform smoke test with dynamic projects

### PR DESCRIPTION
**Pull request by chaodaiG**
Use projects pool manager boskos for managing GCP projects

Boskos not deployed yet
/cc chaodaiG
/assign chaodaiG

### CODE REVIEW

**Comment by chaodaiG** [comment]
Ready for review

/cc @sethvargo @icco

**Review by sethvargo — APPROVED** [review]
/lgtm

Gonna assume it's okay for those URLs to be public?

**Comment by chaodaiG** [comment]
Yeah, that URL is an in cluster endpoint, there is no way it could be reached from outside of prow build cluster

**Pull request merged**
