### PR TITLE
Update healthauthority.html

### PR DESCRIPTION
**Pull request by raghvenders**
## Proposed Changes

* Correcting spell mistake in AudienceBlock input notes as "Value"

**Release Note**

```release-note
NONE
```

### CODE REVIEW

**Comment by sethvargo** [comment]
Hey @raghvenders - this looks great, but can you please sign the CLA? We can't merge contributions without a CLA.

**Comment by raghvenders** [comment]
> Hey @raghvenders - this looks great, but can you please sign the CLA? We can't merge contributions without a CLA.

**Comment by raghvenders** [comment]
@googlebot I signed it!

**Pull request merged**
