### PR TITLE
Update handler.go

### PR DESCRIPTION
**Pull request by andrebriggs**
Logging typo fix

### CODE REVIEW

**Comment by andrebriggs** [comment]
@googlebot I signed it!

**Comment by sethvargo** [comment]
Hi @andrebriggs - thank you for the PR. The system is having a hard time finding your CLA, specifically:

> The email used to register you as an authorized contributor must be the email used for the Git commit. Check your existing CLA data and verify that your email is set on your git commits.

and

> The email used to register you as an authorized contributor must also be attached to your GitHub account.

Can you please take a look?

/ok-to-test
/lgtm
/approve

**Comment by andrebriggs** [comment]
@google-oss-robot 	

/check-cla

**Comment by andrebriggs** [comment]
@google-oss-robot @googlebot 

/check-cla

**Comment by andrebriggs** [comment]
@google-oss-robot @googlebot /retest

**Comment by mikehelmick** [comment]
thanks for the fix

**Pull request merged**
