### PR TITLE
Enable to use scripts/presubmit.sh as a pre-push git hook

### PR DESCRIPTION
**Pull request by alcortesm**
The CONTRIBUTING.md file suggests the presubmit script can be used as a
pre-push git hook but it fails because the script relies on being stored
in a directory directly below the project root and the git hooks are
stored two levels below it.

The current patch allows to run the checks as a pre-push git hook while
still being able to run it by direct invocation.

### CODE REVIEW

**Comment by sethvargo** [comment]
Hi @alcortesm 

We should remove this recommendation from the README instead.

**Comment by alcortesm** [comment]
Ok, I'll add a new commit restoring the previous changes and removing the recommendation.

**Comment by alcortesm** [comment]
Hi @sethvargo 

Please take a look now, a squash-merge might be in order.

**Comment by sethvargo** [comment]
Thanks!

**Comment by alcortesm** [comment]
You are welcome! 😀

**Pull request merged**
