### PR TITLE
Remove unused db struct tags

### PR DESCRIPTION
**Pull request by sethvargo**
General cleanup, these aren't used

### CODE REVIEW

**Comment by sherifkozman** [comment]
upgrading 1 week+ old commits break exisiting Cloud run deployments because deployment scripts do not take into account changing variables names in Cloud Run such as `dbPassword` to `db-password`

**Comment by mikehelmick** [comment]
> upgrading 1 week+ old commits break exisiting Cloud run deployments because deployment scripts do not take into account changing variables names in Cloud Run such as `dbPassword` to `db-password` 

Is there a concern with the naming in this change?

Or there a problem somewhere else?

**Comment by sherifkozman** [comment]
The problem occurs when a project proviosned with older terraform configs , the scripts dont reflects those changes and thus services fail to deploy. So the deployment isnt backward compatible and may require removing all services and deploying them again.

**Comment by sethvargo** [comment]
Hi @sherifkozman. The project is iterating rapidly and we have made some non-BC changes in both the code and Terraform configurations. If you have specific issues, I'd be happy to help you resolve them.

**Comment by sherifkozman** [comment]
@sethvargo Thanks, i have implemented the required fixes to our exisiting implementation but i was noting some breaking changes that would affect anyone who have previously deployed it and it might be noted somewhere if it wont be handled. 
Other than that all good

**Pull request merged**
