### PR TITLE
Docs for Estimating Costs

### PR DESCRIPTION
**Pull request by crwilcox**
#632

### CODE REVIEW

**Comment by mikehelmick** [comment]
> It would be great to add a minimum configuration estimate as well.

I think it depends on what you mean by minimum configuration. Like a dev instance?
Or a small production instance?

size of production instances depends on the number of users and estimated infection rates.

**Comment by sherifkozman** [comment]
@mikehelmick The updates @crwilcox has pushed gives a decent indication of how to calculate resources with some fine tuning such as using CDN and possible use of a non managed PostgreSQL will bring costs even more down. But this is the decision of the HA on how to manage and run infrastructure options.

**Comment by crwilcox** [comment]
@sherifkozman I am going to leave the network egress estimate as $10k+. Assuming US only traffic it may be closer to $6k, but if to AU it is $11.5k. And I would rather err on the side of overestimating, especially since I have already assumed partial adoption.

@krishnadurai I can add the smaller sql instance we mention for dev environments but to @mikehelmick point it is hard to give a minimum deployment without knowing the space it is being deployed for.

**Pull request merged**
