### PR TITLE
Use KeyVault SDK authorizer, which is more flexible

### PR DESCRIPTION
**Pull request by nmiodice**
The SDK provided authorizer used in this PR is a beneficial one to use because of the following:

* It wraps the logic implemented here and therefore will be less of a maintenance overhead
* It provides the ability to authenticate with any of the following methods, with a built in fallback mechanism:
  * Client credentials
  * Client certificate
  * Username password
  * Managed Identity

### CODE REVIEW

**Comment by sethvargo** [comment]
/ok-to-test
/approve
/lgtm

@ultimateboy FYI

**Comment by sethvargo** [comment]
Hey @nmiodice - can you run `go mod tidy` and `go mod verify` please?

**Comment by nmiodice** [comment]
ran `go mod tidy && go mod verify`

**Comment by yordanosgeremew** [comment]
Google.com signs help in can't challenge 
A cant email account help

**Comment by sethvargo** [comment]
(Removed spam comment)

**Pull request merged**
