### PR TITLE
Fix uses of time.Truncate

### LINKED ISSUE #1089: Audit all uses of `time.Truncate`
### TL;DR

https://github.com/google/exposure-notifications-verification-server/issues/819

The linked bug was found in the verification server, and it's likely it exists through this code base. Audit all uses of time's Truncate, and make sure we aren't a full day behind.

### PR DESCRIPTION
**Pull request by jeremyfaller**
**** NB ****
This PR will be marked HOLD until all reviews requested on this PR give
it an LGTM. If you want to HOLD this CL, please add yourself as
reviewer, and mark yourself as NON-LGTM.
**** /NB ****

PTAL. These are all references to Truncate that:

grep -R Truncate * | grep 24

returned, and I think all changes are correct. Please verify.

Fixes #1089

### CODE REVIEW

**Comment by jeremyfaller** [comment]
/hold

PTAL, despite the hold.

**Review by sethvargo — APPROVED** [review]
/lgtm

**Comment by jeremyfaller** [comment]
Any other comments before submission?

**Comment by sethvargo** [comment]
:shipit:

**Review by mikehelmick — APPROVED** [review]

**Pull request merged**
